package com.arca.rengine.model;

/**
* This class was automatically generated by the data modeler tool.
*/

public class InvoiceDetails implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private java.lang.Integer inv_no;
    private java.lang.Double ebs_amt;
    private java.lang.Double remitt_amt;

    public InvoiceDetails() {
    }

    public java.lang.Integer getInv_no() {
        return this.inv_no;
    }

    public void setInv_no(java.lang.Integer inv_no) {
        this.inv_no = inv_no;
    }

    public java.lang.Double getEbs_amt() {
        return this.ebs_amt;
    }

    public void setEbs_amt(java.lang.Double ebs_amt) {
        this.ebs_amt = ebs_amt;
    }

    public java.lang.Double getRemitt_amt() {
        return this.remitt_amt;
    }

    public void setRemitt_amt(java.lang.Double remitt_amt) {
        this.remitt_amt = remitt_amt;
    }

    public InvoiceDetails(java.lang.Integer inv_no, java.lang.Double ebs_amt,
            java.lang.Double remitt_amt) {
        this.inv_no = inv_no;
        this.ebs_amt = ebs_amt;
        this.remitt_amt = remitt_amt;
    }
}