package com.arca.rengine.model;

/**
* This class was automatically generated by the data modeler tool.
*/

public class RObjectInList implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private java.util.List<com.arca.rengine.model.RObjectIn> pCustomer;

    public RObjectInList() {
    }

    public java.util.List<com.arca.rengine.model.RObjectIn> getpCustomer() {
        return this.pCustomer;
    }

    public void setpCustomer(
            java.util.List<com.arca.rengine.model.RObjectIn> pCustomer) {
        this.pCustomer = pCustomer;
    }

    public RObjectInList(java.util.List<com.arca.rengine.model.RObjectIn> pCustomer) {
        this.pCustomer = pCustomer;
    }
}