package com.arca.rengine.model;

/**
* This class was automatically generated by the data modeler tool.
*/

public class RObjectIn implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private java.lang.Integer cust_acct_no;
    private java.lang.Integer cocd;
    private java.lang.Boolean has_cust_match;
    private java.lang.String pymt_adv_no;
    private java.lang.Boolean has_inv_count_match;
    private java.lang.Boolean has_inv_sum_match;
    private java.lang.Boolean has_inv_numbr_match;
    private java.util.List<com.arca.rengine.model.InvoiceDetails> inv_dtl;
    private java.lang.String posting_rule_flag;

    public RObjectIn() {
    }

    public java.lang.Integer getCust_acct_no() {
        return this.cust_acct_no;
    }

    public void setCust_acct_no(java.lang.Integer cust_acct_no) {
        this.cust_acct_no = cust_acct_no;
    }

    public java.lang.Integer getCocd() {
        return this.cocd;
    }

    public void setCocd(java.lang.Integer cocd) {
        this.cocd = cocd;
    }

    public java.lang.Boolean getHas_cust_match() {
        return this.has_cust_match;
    }

    public void setHas_cust_match(java.lang.Boolean has_cust_match) {
        this.has_cust_match = has_cust_match;
    }

    public java.lang.String getPymt_adv_no() {
        return this.pymt_adv_no;
    }

    public void setPymt_adv_no(java.lang.String pymt_adv_no) {
        this.pymt_adv_no = pymt_adv_no;
    }

    public java.lang.Boolean getHas_inv_count_match() {
        return this.has_inv_count_match;
    }

    public void setHas_inv_count_match(java.lang.Boolean has_inv_count_match) {
        this.has_inv_count_match = has_inv_count_match;
    }

    public java.lang.Boolean getHas_inv_sum_match() {
        return this.has_inv_sum_match;
    }

    public void setHas_inv_sum_match(java.lang.Boolean has_inv_sum_match) {
        this.has_inv_sum_match = has_inv_sum_match;
    }

    public java.lang.Boolean getHas_inv_numbr_match() {
        return this.has_inv_numbr_match;
    }

    public void setHas_inv_numbr_match(java.lang.Boolean has_inv_numbr_match) {
        this.has_inv_numbr_match = has_inv_numbr_match;
    }

    public java.util.List<com.arca.rengine.model.InvoiceDetails> getInv_dtl() {
        return this.inv_dtl;
    }

    public void setInv_dtl(
            java.util.List<com.arca.rengine.model.InvoiceDetails> inv_dtl) {
        this.inv_dtl = inv_dtl;
    }

    public java.lang.String getPosting_rule_flag() {
        return this.posting_rule_flag;
    }

    public void setPosting_rule_flag(java.lang.String posting_rule_flag) {
        this.posting_rule_flag = posting_rule_flag;
    }

    public RObjectIn(java.lang.Integer cust_acct_no, java.lang.Integer cocd,
            java.lang.Boolean has_cust_match, java.lang.String pymt_adv_no,
            java.lang.Boolean has_inv_count_match,
            java.lang.Boolean has_inv_sum_match,
            java.lang.Boolean has_inv_numbr_match,
            java.util.List<com.arca.rengine.model.InvoiceDetails> inv_dtl,
            java.lang.String posting_rule_flag) {
        this.cust_acct_no = cust_acct_no;
        this.cocd = cocd;
        this.has_cust_match = has_cust_match;
        this.pymt_adv_no = pymt_adv_no;
        this.has_inv_count_match = has_inv_count_match;
        this.has_inv_sum_match = has_inv_sum_match;
        this.has_inv_numbr_match = has_inv_numbr_match;
        this.inv_dtl = inv_dtl;
        this.posting_rule_flag = posting_rule_flag;
    }
}